name: cd
on:
  push:
    branches: ["main"]

jobs:
  build and push:
    runs-on: ubuntu-latest
    env:
        IMAGE_NAME: iamdude12/frontend
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t ${{env.IMAGE_NAME}} --platform linux/amd64 .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - name: push image
        run: docker push ${{env.IMAGE_NAME}}
