name: cd
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        IMAGE_NAME: frontend
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t ${{env.IMAGE_NAME}} .